### ISSUE TITLE
Initialisation error

### ISSUE THREAD

**Issue by shaurya0406** [gfurtadoalmeida/esp32-driver-nextion#1]
I am getting this error:
E (371) example: could not init nextion device

and I don't think its a hardware issue as I am able to communicate with Nextion display using Arduino library on UART2 ie Serial2 in Arduino.

**Comment by shaurya0406** [comment]
I was referring to this code

https://github.com/gfurtadoalmeida/esp32-driver-nextion/blob/master/examples/listen_button_released.c

and I am using ESP-IDF

**Comment by gfurtadoalmeida** [comment]
I've just transfered it :thumbsup:
Give me some hours while I try that code on my hardware.

**Comment by gfurtadoalmeida** [comment]
Hi @shaurya0406 can you try it? You'll need to delete and clone again because the submodule (iot-lib-nextion) was updated.
All tests passed and it worked on my hardware.

**Comment by shaurya0406** [comment]
Yes, it's working properly.
Thank you.
