### ISSUE TITLE
Nextion: failed initializing display

### ISSUE THREAD

**Issue by oswatt55** [gfurtadoalmeida/esp32-driver-nextion#4]

**Comment by oswatt55** [comment]
i got the issue below, can you help me?
My project is in eclipse, I´m using nextion NX4832T035_011.
In your exemple i get this In the terminal 
![terminal](https://user-images.githubusercontent.com/48256936/126193924-867486de-099c-45ab-b7d1-629fd25550da.PNG)
in the code of nextion.c 
![nextion_init](https://user-images.githubusercontent.com/48256936/126194382-7486af6d-22f7-41e1-81b1-097bf7b63dc2.PNG)

**Comment by gfurtadoalmeida** [comment]
Sure! Could you please tell:
* What is the baud rate configured on your Nextion device? The log shows that the library is using `115200`.
* Are you using the example code or a custom one? In case of a custom one, could you share it?
* Have you tried using a different library? If both fails, the wiring might be misconfigured.

**Comment by oswatt55** [comment]
Thanks.
My baud rate is 115200.
I´m using the exemple
Not, i have only used your library

**Comment by gfurtadoalmeida** [comment]
Ok. I'll take a look at that after work.
Unfortunately, I don't have a Nextion device anymore, so will test with the simulator, using your NX4832T035_011.

**Comment by oswatt55** [comment]
Thank you very much.

**Comment by oswatt55** [comment]
It already works, I needed to specify in the nextion editor the baud rate baude=115200, but now I have these errors, I'll keep checking the causes
![nextion_init](https://user-images.githubusercontent.com/48256936/126226874-21151920-dbaa-4199-9ba0-df9a1b9f5f8e.PNG)

**Comment by gfurtadoalmeida** [comment]
Nice! The [Installation Wiki](https://github.com/gfurtadoalmeida/esp32-driver-nextion/wiki/Installation) was updated with this information. 
What really need be done, in the future, is the implementation of an automatic baud rate detection.

I can't reproduce the `sync error` error. I've just cloned the repo, copied the example code to `main.c` and flashed/ran. Everything worked fine.

What values are being set on `CONFIG_NEX_UART_*` params?
The `CONFIG_NEX_UART_MUTEX_WAIT_TIME_MS` parameter is used as a timeout when trying to acquire a mutex. A very low value could cause this problem.

What is your ESP-IDF version?

**Comment by oswatt55** [comment]
My params in the file config.h
![Captura](https://user-images.githubusercontent.com/48256936/126343259-0aa19ea9-22f6-49e0-b3c3-a3cc2f125ad8.PNG)
ESP-IDF version 4.3

**Comment by gfurtadoalmeida** [comment]
Could you clone it again, copy the example code to `main.c`, flash and run? I've tried again but could not reproduce the problem.

**Comment by oswatt55** [comment]
okey, It already works, thanks Gabriel

**Comment by gfurtadoalmeida** [comment]
Nice! What was the problem?

**Comment by oswatt55** [comment]
My solution was to comment the line of code, nextion_core_command_sync_acquire and I was able to receive text without problem
![Captura](https://user-images.githubusercontent.com/48256936/126820741-9bc02262-cf9e-4d08-b282-eb2ce673e671.PNG)

**Comment by oswatt55** [comment]
my code had errors. I came back again with your example and it works correctly

**Comment by oswatt55** [comment]
Do you have an example of the nextion_component_set_property_text function?
I am confused with "property_name"

**Comment by gfurtadoalmeida** [comment]
Nice! I do not have an official example, but you can look at [this test](https://github.com/gfurtadoalmeida/esp32-driver-nextion/blob/master/components/nextion/test/nextion/component_test.c#L156).

The function `nextion_component_set_property_text` sets a component property to the text value passed on the `text` parameter.
The `property_name` is the name of the property you want to set. For this function, the property being set **must accept text**.

Let's say you have a textbox name "t0" and you want to set its text to "Hello World", in this case the `property_name` would be "txt".
You can get the property name in the component's property tab (example below). Every component has different properties.

![image](https://user-images.githubusercontent.com/27151609/127930677-48b78cd5-b712-490c-a32c-9b5c5a463d13.png)

**Comment by oswatt55** [comment]
thanks for your explanation and example, my project works correctly, thank you very much

**Comment by gfurtadoalmeida** [comment]
Happy to help!
