### ISSUE TITLE
Touch event callback not getting called

### ISSUE THREAD

**Issue by stijnb1234** [gfurtadoalmeida/esp32-driver-nextion#8]
### Description

I implemented the driver using the example in the README. When I touch my screen, I don't get a call on the callback.

### Reproduction Steps

1. Use example code.
2. Upload screen to Nextion device.
3. No callback is getting called.

### Expected behavior

It should just call the callback function.

### Actual behavior

Nothing

### Display serie.

Discovery

### Display model.

NX4832F035

### IDF version.

v5.2.1

### Espressif SoC revision.

ESP32-WROOM-32U

### Other information

Do I need to change anything in the Nextion config / scripts to make the callback event work?

```java
bool Touchscreen::init() {
  nextion = nextion_driver_install(TOUCH_UART_PORT, TOUCH_BAUDRATE,
                                   TOUCH_TX_PIN, TOUCH_RX_PIN);
  ESP_OK_CHECK_RETURN(nextion_init(nextion));

  if (!nextion_event_callback_set_on_touch(nextion, callback_touch_event)) {
    ESP_LOGE(TAG, "Failed to set touch event callback");
    return false;
  }

  return true;
}

/* static */ void Touchscreen::callback_touch_event(nextion_on_touch_event_t event) {
  ESP_LOGI(TAG, "Touch event: page_id=%d, component_id=%d", event.page_id,
           event.component_id);
}
```

**Comment by gfurtadoalmeida** [comment]
Hi @stijnb1234, please provide the logs sent to the terminal.

**Comment by stijnb1234** [comment]
Issue resolved, I feel a bit dumb now, you have to check the "Send Component ID" checkbox in the Editor on the buttons you want to get the event called for.

**Comment by gfurtadoalmeida** [comment]
No problems, I've done that too 😄 

The documentation was updated, with your observation added at [Configure Component for Touch](https://github.com/gfurtadoalmeida/esp32-driver-nextion/blob/master/docs/wiki/how_to_use.md#2-configure-for-touch-event-optional).
